### ISSUE TITLE
Android - Video stops after pre-roll

### ISSUE THREAD

**Issue by ghost** [vix-simplex/clappr-ad-plugin#1]
When try the demo on android (Chrome and Native browser). 
After I click play it starts playing Pre-roll - Preroll finishes it goes back to showing play button.
I click play then it starts main video.

This breaks the experience. Main video should just start after pre-roll.
Great job on plugin.

**Comment by va-an** [comment]
@vmm2013 Thanks for your attention. Yes, I know this bug and I'll fix it later. Right now I focused on main functionality (not all finished as should be).

**Comment by va-an** [comment]
@vmm2013 I have update for this issue. This problem not in plugin, this is a normal behavior for mobile browsers. Proofs:
https://github.com/clappr/clappr/issues/404
https://bugs.chromium.org/p/chromium/issues/detail?id=159336
https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html

But I will try fix autoplay after ad-video ends.

**Comment by va-an** [comment]
@vmm2013, i'm in process fixing this bug, pre-version for preroll available [here](http://d11.cdnvideo.ru/videojs/clappr/cvap2/cvap2.html). 
In this version there bug, but I'm opened [issue](https://github.com/clappr/clappr/issues/1245) in clappr-repo already.
