### ISSUE TITLE
Demo links are not working!

### ISSUE THREAD

**Issue by AnanthKongu** [vix-simplex/clappr-ad-plugin#2]
Hi,
      The demo links are not working, it throws (Cannot read property 'ads' of undefined) error, have any idea...

**Comment by va-an** [comment]
Thanks for your attention, i will fix it soon (I will write to you).

18 Дек 2016 г. 16:24 пользователь "AnanthKongu" <notifications@github.com>
написал:

**Comment by AnanthKongu** [comment]
np, thanks :)

**Comment by va-an** [comment]
@AnanthKongu demo works now

**Comment by ananth2020** [comment]
Yep, Thanks

**Comment by AnanthKongu** [comment]
Yep, Thanks!
