### ISSUE TITLE
VAST 3.0

### ISSUE THREAD

**Issue by churu88** [vix-simplex/clappr-ad-plugin#4]
Hi!
I'm trying to use this vast url (3.0) but it doesn't work with your plugin.

https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/40327789/www.lared.am/Home/Home_VideoPreroll&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=[description_url]&correlator=[timestamp]

**Comment by va-an** [comment]
@churu88 I checked this link [here](https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector) and this link look like a ad-banner in bottom of player. My plugin work with preroll/pauseroll ad-**video** only yet.

**Comment by churu88** [comment]
Oh, maybe it depends on the country, because I see a preroll and all of us see a preroll.

Look at the original web with this vast:

http://www.lared.am/

It should show a preroll.

I tryed also in video inspector and shows me video preroll.

![image](https://cloud.githubusercontent.com/assets/23558737/22931281/d1ca9492-f2a2-11e6-9c7b-37fd204060cb.png)

Regards!

**Comment by churu88** [comment]
Do you have any example working? Regards

**Comment by va-an** [comment]
@churu88 [this](http://d11.cdnvideo.ru/videojs/clappr/test/demo_preroll.html) should work (works for me just now).

**Comment by meysamzandy** [comment]
hi,
i tried to use revive vast xml:
http://meysamzandy.ir/revive/www/delivery/fc.php?script=bannerTypeHtml:vastInlineBannerTypeHtml:vastInlineHtml&format=vast&nz=1&zones=pre-roll%3D2
with your plugin but it doesn't work.
would you help me?

**Comment by va-an** [comment]
@meysamzandy, hello! Sorry, but I'm not working on this project anymore. Feel free for forking and continue developing!
