### ISSUE TITLE
DFP ad tag not playing

### ISSUE THREAD

**Issue by iflixweb** [vix-simplex/clappr-ad-plugin#5]
Hello!,is the dfp ads and adotube ad tag supported.,with this plugin?
it's not work for me.Can you checked?

Link: 

1) http://iflixweb.stream/video-player/pre.html
2). http://iflixweb.stream/video-player/test.php

other/your demo ad tag playing fine.

http://iflixweb.stream/video-player/

i am looking for help for integrate dfp

**Comment by va-an** [comment]
Hello @iflixweb.
I'm sorry, I forgot write in README.md that I stopped work about this repo. Sorry again.
